site_name: Documentation PFR
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
  palette:
    scheme: default
  language: fr
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
nav:
  - Accueil: index.md 
  - Conception: 
    - Introduction: conception/index.md
    - Testabilité: conception/test.md
  - Gestion de projet:
    - Introduction: gestion/index.md
    - Versioning: gestion/git.md
    - gestion/sprint.md
  - Sécurité: 
    - Checklist: securite/index.md
    - Danger des dépendances: securite/dependances.md
  - Critères de Qualité:
    - Introduction: qualite/index.md
    - Testabilité: qualite/tests.md
  - Documentation: 
    - Introduction: documentation/index.md
    - Documentation API: documentation/api.md
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      toc_depth: 1-2
  - pymdownx.tasklist:
      custom_checkbox: true
