site_name: Documentation PFR
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Accueil: index.md 
  - Conception: 
    - conception/index.md
  - Gestion de projet:
    - Introduction: gestion/index.md
    - Versioning: gestion/git.md
  - Sécurité: 
    - Checklist: securite/index.md
  - Documentation: 
    - Introduction: documentation/index.md
    - Documentation API: documentation/api.md
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      toc_depth: 1-2
  - pymdownx.tasklist:
      custom_checkbox: true
