site_name: Documentation PFR
theme:
  name: material
nav:
  - Accueil: index.md 
  - Sécurité: securite.md
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
